export const FETCH_DIVISION_LIST = "FETCH_DIVISION_LIST";
export const PLACES_BY_ID = "PLACES_BY_ID";
export const FETCH_PLACE_BY_ID = "FETCH_PLACE_BY_ID";
export const FETCH_PLACE_FROM_BOOKMARK = "FETCH_PLACE_FROM_BOOKMARK";
export const REMOVE_PLACES_BY_ID = "REMOVE_PLACES_BY_ID";

